/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-13 09:46:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-family:Arial, Helvetica, sans-serif;\r\n");
      out.write("    background:linear-gradient(135deg,#eef2f7,#dbe7ff);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header{\r\n");
      out.write("    background:linear-gradient(90deg,#004080,#0066cc);\r\n");
      out.write("    color:white;\r\n");
      out.write("    padding:25px 0;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-size:22px;\r\n");
      out.write("    letter-spacing:1px;\r\n");
      out.write("    box-shadow:0 4px 10px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("    max-width:900px;\r\n");
      out.write("    margin:40px auto;\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    display:grid;\r\n");
      out.write("    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("    gap:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card{\r\n");
      out.write("    background:white;\r\n");
      out.write("    padding:25px 20px;\r\n");
      out.write("    border-radius:15px;\r\n");
      out.write("    box-shadow:0 6px 18px rgba(0,0,0,0.08);\r\n");
      out.write("    transition:all 0.25s ease;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    flex-direction:column;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover{\r\n");
      out.write("    transform:translateY(-5px) scale(1.01);\r\n");
      out.write("    box-shadow:0 10px 25px rgba(0,0,0,0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h3{\r\n");
      out.write("    margin:0 0 15px 0;\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("    color:#004080;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card a{\r\n");
      out.write("    padding:10px 20px;\r\n");
      out.write("    background:#004080;\r\n");
      out.write("    color:white;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("    transition:0.2s;\r\n");
      out.write("    margin-top:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card a:hover{\r\n");
      out.write("    background:#0073e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".balance{\r\n");
      out.write("    font-size:32px;\r\n");
      out.write("    color:#00a65a;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("    margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <h2>Xin Chào, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("</header>\r\n");
 Model.Account acc=(Model.Account ) session.getAttribute("Account");
if(acc!= null){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3>So du tai khoan</h3>\r\n");
      out.write("        <p class=\"balance\"><strong>");
      out.print( String.format("%,.0f",acc.getBalance()) );
      out.write("</strong></p>\r\n");
      out.write("    </div>\r\n");

    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3>Chuyen tien</h3>\r\n");
      out.write("        <a href=\"transfer.jsp\">Thực hiện ngay</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3>Lịch sử giao dịch</h3>\r\n");
      out.write("        <a href=\"history.jsp\">Xem chi tiết giao dịch</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3>Hỗ trợ</h3>\r\n");
      out.write("        <a href=\"support.jsp\"> Gửi Hỗ Trợ</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <a href=\"logout\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
